# Generated by Django 5.2.7 on 2026-06-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_remove_post_num_of_likes_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='bool',
            field=models.BooleanField(default=False),
        ),
    ]
