# Generated by Django 5.2.7 on 2026-06-24 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_like_bool'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='bool',
            new_name='liked',
        ),
    ]
