# Generated by Django 5.2.7 on 2026-06-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_rename_bool_like_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='liked',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
